name: Transifex 🗺

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.ui'


jobs:
  push:
    name: Push to Transifex
    runs-on: ubuntu-latest
    if: github.repository == 'Artelia/Mesh_tools'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - uses: actions/cache@v4.2.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/packaging.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python requirements
      run: pip install -r requirements/packaging.txt

    - name: Push to Transifex
      run: qgis-plugin-ci push-translation ${{ secrets.TRANSIFEX_TOKEN }}
